OK = 0
FAILED = 1
NOT_LOGGED_IN = 2
USERNAME_EXISTS = 3
WRONG_PASSWORD = 4
USER_DOES_NOT_EXIST = 5
UNAUTHORIZED = 6

PROJECT_ADVANCE_ALREADY_REQUESTED = 7
CONSULTANT_NOT_IN_PROJECT = 8
MANAGER_HAS_ACTIVE_PROJECTS = 9
NOT_ADVANCED = 10

DES = 11
CON = 12
IDV = 13

USER_ALREADY_IN_PROJECT = 14
PROJECT_DOES_NOT_EXIST = 15